name = "mcp-smartscout"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Environment variables (set these in Cloudflare dashboard or via wrangler secret)
# [vars]
# DOMO_INSTANCE = "your-instance"
# DOMO_ACCESS_TOKEN = "your-token"

# KV namespace for rate limiting
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "your-kv-namespace-id"

# D1 database for API keys (optional)
# [[d1_databases]]
# binding = "DB"
# database_name = "mcp-smartscout"
# database_id = "your-database-id"

# Durable Objects for stateful connections (if needed)
# [[durable_objects.bindings]]
# name = "MCP_SESSION"
# class_name = "MCPSession"

# [[migrations]]
# tag = "v1"
# new_classes = ["MCPSession"]

[env.production]
# Production environment variables