name = "smartscout"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Environment variables (set these in Cloudflare dashboard or via wrangler secret)
# [vars]
# DOMO_INSTANCE = "your-instance"
# DOMO_ACCESS_TOKEN = "your-token"

# KV namespace for rate limiting - TEMPORARILY DISABLED
# To enable rate limiting:
# 1. Create KV namespace in Cloudflare dashboard
# 2. Uncomment and update the ID below
# [[kv_namespaces]]
# binding = "RATE_LIMIT"
# id = "your-actual-kv-namespace-id"

[env.production]
# Production environment variables